/* Auto-generated by genmsg_cpp for file /home/giuseppe/catkinAIRobotsUnina_ws/src/AIRobots_Unina_workspace/ibvs_formation_bearing/msg/bearing.msg */
#ifndef IBVS_FORMATION_BEARING_MESSAGE_BEARING_H
#define IBVS_FORMATION_BEARING_MESSAGE_BEARING_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ibvs_formation_bearing
{
template <class ContainerAllocator>
struct bearing_ {
  typedef bearing_<ContainerAllocator> Type;

  bearing_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , scale(0.0)
  {
  }

  bearing_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , scale(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef double _scale_type;
  double scale;


  typedef boost::shared_ptr< ::ibvs_formation_bearing::bearing_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ibvs_formation_bearing::bearing_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct bearing
typedef  ::ibvs_formation_bearing::bearing_<std::allocator<void> > bearing;

typedef boost::shared_ptr< ::ibvs_formation_bearing::bearing> bearingPtr;
typedef boost::shared_ptr< ::ibvs_formation_bearing::bearing const> bearingConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ibvs_formation_bearing::bearing_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ibvs_formation_bearing::bearing_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ibvs_formation_bearing

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ibvs_formation_bearing::bearing_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ibvs_formation_bearing::bearing_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ibvs_formation_bearing::bearing_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b44c119611b71941ba5d06f61c311ea8";
  }

  static const char* value(const  ::ibvs_formation_bearing::bearing_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb44c119611b71941ULL;
  static const uint64_t static_value2 = 0xba5d06f61c311ea8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ibvs_formation_bearing::bearing_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ibvs_formation_bearing/bearing";
  }

  static const char* value(const  ::ibvs_formation_bearing::bearing_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ibvs_formation_bearing::bearing_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 scale\n\
";
  }

  static const char* value(const  ::ibvs_formation_bearing::bearing_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ibvs_formation_bearing::bearing_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ibvs_formation_bearing::bearing_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.scale);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct bearing_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ibvs_formation_bearing::bearing_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ibvs_formation_bearing::bearing_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "scale: ";
    Printer<double>::stream(s, indent + "  ", v.scale);
  }
};


} // namespace message_operations
} // namespace ros

#endif // IBVS_FORMATION_BEARING_MESSAGE_BEARING_H

